<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="5" failed="2" ignored="0" total="7" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="39046" started-at="2017-11-28T07:26:56Z" finished-at="2017-11-28T07:27:35Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="39046" started-at="2017-11-28T07:26:56Z" finished-at="2017-11-28T07:27:35Z">
      <class name="com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords@2ed0fbae]" name="setUp" is-config="true" duration-ms="10" started-at="2017-11-28T02:26:56Z" finished-at="2017-11-28T02:26:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="setUp1()[pri:0, instance:com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords@2ed0fbae]" name="setUp1" is-config="true" duration-ms="8046" started-at="2017-11-28T02:26:56Z" finished-at="2017-11-28T02:27:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp1 -->
        <test-method status="FAIL" signature="verifiyLoginWithDifferentRecords(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords@2ed0fbae]" name="verifiyLoginWithDifferentRecords" duration-ms="15016" started-at="2017-11-28T02:27:05Z" data-provider="loginData" finished-at="2017-11-28T02:27:20Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[yogeshsolanki@rangam.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[rangam@123]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[y]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.internal.thread.ThreadTimeoutException">
            <message>
              <![CDATA[Method com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords.verifiyLoginWithDifferentRecords() didn't finish within the time-out 15000]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords.verifiyLoginWithDifferentRecords() didn't finish within the time-out 15000
	at java.lang.Throwable.printStackTrace(Throwable.java:643)
	at java.lang.Throwable.printStackTrace(Throwable.java:634)
	at com.test.automation.UIAutomation.uiActions.LoginPage.loginToApplication(LoginPage.java:70)
	at com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords.verifiyLoginWithDifferentRecords(VerifiyLoginWithDifferentRecords.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.thread.ThreadTimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifiyLoginWithDifferentRecords -->
        <test-method status="FAIL" signature="verifiyLoginWithDifferentRecords(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords@2ed0fbae]" name="verifiyLoginWithDifferentRecords" duration-ms="15002" started-at="2017-11-28T02:27:20Z" data-provider="loginData" finished-at="2017-11-28T02:27:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[xyz@rangam.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[wtc@2017]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[y]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.internal.thread.ThreadTimeoutException">
            <message>
              <![CDATA[Method com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords.verifiyLoginWithDifferentRecords() didn't finish within the time-out 15000]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords.verifiyLoginWithDifferentRecords() didn't finish within the time-out 15000
	at java.lang.Thread.interrupt(Thread.java:916)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
	at com.test.automation.UIAutomation.testBase.TestBase.waitForVisitibilty(TestBase.java:270)
	at com.test.automation.UIAutomation.testBase.TestBase.isElementPresent(TestBase.java:298)
	at com.test.automation.UIAutomation.uiActions.LoginPage.loginToApplication(LoginPage.java:66)
	at com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords.verifiyLoginWithDifferentRecords(VerifiyLoginWithDifferentRecords.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.thread.ThreadTimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifiyLoginWithDifferentRecords -->
        <test-method status="SKIP" signature="verifiyLoginWithDifferentRecords(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords@2ed0fbae]" name="verifiyLoginWithDifferentRecords" duration-ms="5" started-at="2017-11-28T02:27:35Z" data-provider="loginData" finished-at="2017-11-28T02:27:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Test1@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[n]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping this exception]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping this exception
	at com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords.verifiyLoginWithDifferentRecords(VerifiyLoginWithDifferentRecords.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifiyLoginWithDifferentRecords -->
        <test-method status="SKIP" signature="verifiyLoginWithDifferentRecords(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords@2ed0fbae]" name="verifiyLoginWithDifferentRecords" duration-ms="4" started-at="2017-11-28T02:27:35Z" data-provider="loginData" finished-at="2017-11-28T02:27:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Test2@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[n]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping this exception]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping this exception
	at com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords.verifiyLoginWithDifferentRecords(VerifiyLoginWithDifferentRecords.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifiyLoginWithDifferentRecords -->
        <test-method status="SKIP" signature="verifiyLoginWithDifferentRecords(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords@2ed0fbae]" name="verifiyLoginWithDifferentRecords" duration-ms="3" started-at="2017-11-28T02:27:35Z" data-provider="loginData" finished-at="2017-11-28T02:27:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Test3@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password3]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[n]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping this exception]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping this exception
	at com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords.verifiyLoginWithDifferentRecords(VerifiyLoginWithDifferentRecords.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifiyLoginWithDifferentRecords -->
        <test-method status="SKIP" signature="verifiyLoginWithDifferentRecords(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords@2ed0fbae]" name="verifiyLoginWithDifferentRecords" duration-ms="5" started-at="2017-11-28T02:27:35Z" data-provider="loginData" finished-at="2017-11-28T02:27:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Test4@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password4]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[n]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping this exception]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping this exception
	at com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords.verifiyLoginWithDifferentRecords(VerifiyLoginWithDifferentRecords.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifiyLoginWithDifferentRecords -->
        <test-method status="SKIP" signature="verifiyLoginWithDifferentRecords(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords@2ed0fbae]" name="verifiyLoginWithDifferentRecords" duration-ms="4" started-at="2017-11-28T02:27:35Z" data-provider="loginData" finished-at="2017-11-28T02:27:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Test5@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password5]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[n]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping this exception]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping this exception
	at com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords.verifiyLoginWithDifferentRecords(VerifiyLoginWithDifferentRecords.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifiyLoginWithDifferentRecords -->
        <test-method status="PASS" signature="close()[pri:0, instance:com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords@2ed0fbae]" name="close" is-config="true" duration-ms="590" started-at="2017-11-28T02:27:35Z" finished-at="2017-11-28T02:27:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- com.test.automation.UIAutomation.tests.VerifiyLoginWithDifferentRecords -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
